// src/main/java/com/fitnesstracker/authservice/service/UserServiceExternal.java

package com.fitnesstracker.authservice.service;

import com.fitnesstracker.authservice.dto.RegistrationRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class UserServiceExternal {

    // In a real application, this URL should be loaded from application.properties
    private static final String USER_SERVICE_BASE_URL = "http://localhost:8081/api/users";

    private final RestTemplate restTemplate = new RestTemplate();

    /**
     * Calls the User Service API to create the user profile after authentication
     * credentials are saved.
     * 
     * @param userId  The unique ID generated by the Auth Service's database.
     * @param request The registration details (email, username, goals, etc.).
     */
    public void createProfile(String userId, RegistrationRequest request) {
        // Create a DTO specifically for the User Service (usually smaller than
        // RegistrationRequest)
        // For simplicity, we reuse the request object here.

        // Note: For production, use a discovery client (e.g., Eureka) instead of a
        // hardcoded URL

        // This is a synchronous call to the external User Service
        ResponseEntity<Void> response = restTemplate.postForEntity(
                USER_SERVICE_BASE_URL + "/create", // POST to User Service
                request,
                Void.class // We don't need a response body
        );

        if (!response.getStatusCode().is2xxSuccessful()) {
            // Log error or implement a retry mechanism (e.g., using a message queue)
            throw new RuntimeException("Failed to create user profile in User Service.");
        }
    }
}