package com.fitnesstracker.authservice.service;

import com.fitnesstracker.authservice.dto.RegistrationRequest;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.HashMap;
import java.util.Map;

@Service
public class UserServiceExternal {

    private static final String USER_SERVICE_BASE_URL = "http://localhost:8081/api/users";
    private final RestTemplate restTemplate = new RestTemplate();

    /**
     * Calls the User Service API to create the user profile after authentication
     * credentials are saved.
     * 
     * @param userId       The unique ID generated by the Auth Service
     * @param email        The user's email
     * @param passwordHash The hashed password
     * @param request      The registration details (name, profileInfo,
     *                     fitnessLevel, goals)
     */
    public void createProfile(String userId, String email, String passwordHash, RegistrationRequest request) {
        // Create a Map to represent the UserProfile object
        // The passwordHash is intentionally NOT sent to the user-service.
        Map<String, Object> userProfile = new HashMap<>();
        userProfile.put("userId", userId);
        userProfile.put("email", email);
        userProfile.put("name", request.getName());
        userProfile.put("profileInfo", request.getProfileInfo());
        userProfile.put("fitnessLevel", request.getFitnessLevel());
        userProfile.put("goals", request.getGoals());

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<Map<String, Object>> entity = new HttpEntity<>(userProfile, headers);

        // This is a synchronous call to the external User Service
        ResponseEntity<Void> response = restTemplate.postForEntity(
                USER_SERVICE_BASE_URL + "/create",
                entity,
                Void.class);

        if (!response.getStatusCode().is2xxSuccessful()) {
            throw new RuntimeException("Failed to create user profile in User Service.");
        }
    }
}