// services/auth-service/src/routes/auth_routes.js

const bcrypt = require('bcryptjs');
const db = require('../db_connect'); // Import your existing database connection

// We recommend using 10 for the salt rounds, as it provides a good balance of security and performance.
const SALT_ROUNDS = 10; 

module.exports = (app) => {
  app.post('/api/auth/register', async (req, res) => {
    const { email, username, password, fitness_goal, preferred_activity } = req.body;

    // 1. Basic Input Validation
    if (!email || !username || !password) {
      return res.status(400).send({ message: 'Missing required fields: email, username, and password.' });
    }

    try {
      // 2. Hash the Password
      const salt = await bcrypt.genSalt(SALT_ROUNDS);
      const password_hash = await bcrypt.hash(password, salt);

      // 3. Define the SQL Query for Insertion
      // Note: user_id is automatically generated by the database (UUID)
      const query = `
        INSERT INTO users (email, username, password_hash, fitness_goal, preferred_activity)
        VALUES ($1, $2, $3, $4, $5)
        RETURNING user_id, email, username; -- Return the user_id for confirmation
      `;
      
      const values = [
        email, 
        username, 
        password_hash, 
        fitness_goal || 'Maintain Fitness', // Use defaults if not provided (from your schema)
        preferred_activity || 'Running'
      ];

      // 4. Execute the Query
      const result = await db.query(query, values);
      const newUser = result.rows[0];

      // Success Response (Do NOT send the password_hash back!)
      res.status(201).send({
        message: 'User registered successfully!',
        user: { 
          id: newUser.user_id, 
          username: newUser.username, 
          email: newUser.email 
        }
      });

    } catch (error) {
      // Handle database errors (e.g., duplicate email/username)
      if (error.code === '23505') { // PostgreSQL code for 'unique_violation'
        return res.status(409).send({ message: 'Email or username already in use.' });
      }
      console.error('Registration Error:', error);
      res.status(500).send({ message: 'Internal server error during registration.' });
    }
  });
};